# This workflow runs all of our lints, tests, and other requirements for merging code.
name: Validate

on: push

jobs:
  validate:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        go-version: [1.13.x, 1.14.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install golangci-lint
        run: |
          wget -q https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCILINT_VERSION}/golangci-lint-${GOLANGCILINT_VERSION}-linux-amd64.tar.gz -O /tmp/golangci-lint.tar.gz
          mkdir /tmp/golangci-lint
          tar -xzf /tmp/golangci-lint.tar.gz -C /tmp/golangci-lint
          cp /tmp/golangci-lint/golangci-lint-${GOLANGCILINT_VERSION}-linux-amd64/golangci-lint ${HOME}/golangci-lint
          rm -rf /tmp/golangci-lint.tar.gz /tmp/golangci-lint
        env:
          GOLANGCILINT_VERSION: 1.23.8 # https://github.com/golangci/golangci-lint/releases
      - name: Checkout
        uses: actions/checkout@v2
      - name: Format
        run: test -z $(gofmt -l -w -s ./)
      - name: Lint
        run: ${HOME}/golangci-lint run
      - name: Test
        run: go test -v -race -cover -coverprofile=coverage.txt ./... | tee -a test-results.txt
      - name: Upload Test Results
        uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: test-results.txt
      - name: Upload Coverage
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage.txt
      - name: Benchmark
        run: |
          for i in {1..5}; do
            go test -run=XXX -bench=. | tee -a bench.txt
          done
      - name: Upload Benchmark
        uses: actions/upload-artifact@v1
        with:
          name: bench-${{ matrix.os }}-${{ matrix.go-version }}
          path: bench.txt
