name: Validate

on: [push]

jobs:
  validate:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.13.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install golangci-lint
        run: |
          wget -q https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCILINT_VERSION}/golangci-lint-${GOLANGCILINT_VERSION}-linux-amd64.tar.gz -O /tmp/golangci-lint.tar.gz
          mkdir /tmp/golangci-lint
          tar -xzf /tmp/golangci-lint.tar.gz -C /tmp/golangci-lint
          cp /tmp/golangci-lint/golangci-lint-${GOLANGCILINT_VERSION}-linux-amd64/golangci-lint ${HOME}/golangci-lint
          rm -rf /tmp/golangci-lint.tar.gz /tmp/golangci-lint
        env:
          GOLANGCILINT_VERSION: 1.23.1
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Format
        run: test -z $(gofmt -l -w -s ./)
      - name: Lint
        run: ${HOME}/golangci-lint run
      - name: Test
        run: go test -v -cover -race
      - name: Benchmark
        run: go test -run=XXX -bench=.
